### ISSUE TITLE
 Chaturbate Followed Cams

### ISSUE THREAD

**Issue by ChoccyStarfish** [dobbelina/repository.dobbelina#1102]
### Bug reports:

When I go into followed cams, I get an error and cannot put in my username etc to login to Chaturbate, fresh install on my new Nvidia Shield.

### OS environment
Android TV 11, Nvidia Shield TV Pro

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. http://paste.kodi.tv/tokefiwize

Any bugreports without logfile will be deleted.

**Comment by ErosVece** [comment]
Fixed: https://github.com/dobbelina/repository.dobbelina/commit/c02b32a878e046502bedf8d15a25f3d25d822c07

**Comment by ChoccyStarfish** [comment]
Thank you, great work.

**Comment by hehewtf** [comment]
downloaded the master with the fix and manually updated the plugin folder

but I'm still getting errors it seems, did I do something wrong?

https://paste.kodi.tv/hejiluliqu

**Comment by ChoccyStarfish** [comment]
I tried after updating, still broken.

**Comment by 12asdfg12** [comment]
Try to delete the cookies from the settings and log in again

**Comment by ChoccyStarfish** [comment]
Hi, Did that, still the same as my original post.

**Comment by 12asdfg12** [comment]
After deleting cookies and entering the user/password again, what happens? Can you access followed cams? Or does it give you a user/password error?
Does the account work on the website?

**Comment by ChoccyStarfish** [comment]
Hello, After deleting cookies, it won't even show me the login, let alone the ability to enter it. Yes my account works fine online.

**Comment by hehewtf** [comment]
iirc it only worked after I hit "Clear local cache" in main menu of Cumination

previously I only cleared cache and cookies through the addon settings, which didn't solve the login issue

![IMG_20230711_085222](https://github.com/dobbelina/repository.dobbelina/assets/73599832/00fd9152-3a81-4d74-9f13-e80c6e70dca4)

**Comment by ChoccyStarfish** [comment]
Hi, Thank you, but that's strange, I've just looked and I don't have that option in main menu, only in add-on settings.

**Comment by hehewtf** [comment]
> Hi, Thank you, but that's strange, I've just looked and I don't have that option in main menu, only in add-on settings.

I think it disappears after you put sites on the main menu

I did do a lot of stuff to try to get it to work, ended up re-installing (backed up favs and stuff)
and Chaturbate login still didn't pop up, when checking the log (posted in my first post above) it looked like cookies somehow messed up the web requests and the addon just kept loading and no login fields ever popped up

but after the re-install I noticed that clear local cache option in main menu, clicked it and I'm pretty sure that solved it (did other things too but that was mainly things I'd already tried before both before and after re-installing)


hopefully it helps

**Comment by ChoccyStarfish** [comment]
Thank you, I'll give this ago, I do have another log captured just in case this doesn't work for me, I'll let you know if it works, cheers.

**Comment by ChoccyStarfish** [comment]
Alas, the above method didn't work for me, did see clear cache in menu though, thanks guys for the input, but I'll start a new thread with a new log, cheers.

**Comment by hehewtf** [comment]
> Alas, the above method didn't work for me, did see clear cache in menu though, thanks guys for the input, but I'll start a new thread with a new log, cheers.

weird issue, probably a combination of things I did then, was a while ago so I don't remember the exact steps sadly

hope it gets solved for you :/
