### ISSUE TITLE
Sites not working xvideos & aagmaal.pro

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#1143]
Hi, some sites working earlier are not working any more. I tried using VPN also. The sites in question are
Error: Could not find supporting host
Site: xvideos
Error: No videos found
Site: aagmaal.pro

Combined Debugging enabled log can be found here. The system.is connected to Surfshark VPN Nepal (Supjav works only through Nepal)

https://paste.kodi.tv/eluxukecad

Please let me know if you need further information.

**Comment by ErosVece** [comment]
First, your script.module.resolveurl.xxx is outdated: 
`info <general>: CAddonMgr::FindAddons: script.module.resolveurl.xxx v2.1.34 installed`

The latest one is 2.1.39: https://github.com/Gujal00/smrzips/blob/master/zips/script.module.resolveurl.xxx/script.module.resolveurl.xxx-2.1.39.zip

If xvideos still don't work, can you run it with debug log enabled, using this modified utils.py?
[utils.txt](https://github.com/dobbelina/repository.dobbelina/files/12313172/utils.txt)
Save as utils.py

Now go to the xvideos video with an error, try to play it, and after the notify, it asks to add diagnosted report to the log.
Press yes, and upload the debug logfile.

**Comment by ErosVece** [comment]
Aagmaal was fixed a few days ago: https://github.com/dobbelina/repository.dobbelina/commit/ba75cd7bfd7002b3acbb8a0cc9873ac6685aa720

**Comment by imurreflection** [comment]
Thank you so much sir. Updating smr resolved the issue for xvideos. However, it still did not resolve the issue for aagmaal pro. Please see debug enabled log below
https://paste.kodi.tv/xakequpani
Since the video plays fine, I did not copy it. Do you want me to use it again to get you debug enabled log for non playing aagmaal pro video sir?

**Comment by imurreflection** [comment]
Dear @erosvece sir. I checked further and found there was no support available in smr for Dood domains. I added the py file manually and all is working now via Nepal vpn . Thank you @gujal00 for providing support to dood. Closing the issue now
