### ISSUE TITLE
[old Kodi] Addon not launching anymore due to one special character in one script :)

### ISSUE THREAD

**Issue by notimp** [dobbelina/repository.dobbelina#1236]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Error can be fixed by replacing the character with an o. :) Addon then launches again.

Error log see:

![Bildschirmfoto 2023-11-26 um 15 46 03](https://github.com/dobbelina/repository.dobbelina/assets/47777453/75dbe1e9-6080-4808-8b16-dbfc69463c01)

### Kodi version

Leia

### Cumination version

1.1.96

### Operating System and version

Android

**Comment by ErosVece** [comment]
Fixed: https://github.com/dobbelina/repository.dobbelina/commit/78310a365ff5036521b66b209f170eaa82b20b6f

**Comment by CatmanT** [comment]
Sorry but still not working. Addon not lunching anymore. Leia.

**Comment by gtr33m** [comment]
As per @CatmanT the error is still present.

https://paste.kodi.tv/omevawacax

If it help
