### ISSUE TITLE
FamilyPornHD streams won't play

### ISSUE THREAD

**Issue by Askank-Man** [dobbelina/repository.dobbelina#1394]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.

### Description

Video streams won't play in Cumination > Sites > familypornhd

**Comment by 12asdfg12** [comment]
fixed https://github.com/dobbelina/repository.dobbelina/commit/8cf21d3f5e6ec724c5ac72c7ee6ca3e0796a9cb2

**Comment by 12asdfg12** [comment]
Yes, it's the same issue as described in #1358.

If your remote lacks a context menu key, you can assign the context menu command to an unused key using the Keymap Editor plugin.

**Comment by Askank-Man** [comment]
Still unable to stream videos in FamilyPornHD in Kodi 21.0.1 on Android 14. "Play from here" also does not work.

**Comment by 12asdfg12** [comment]
The fix will be ​​released in v1.1.113

**Comment by Askank-Man** [comment]
When is v1.1.113 slated for release?

**Comment by dobbelina** [comment]
> When is v1.1.113 slated for release?

28 May

**Comment by Askank-Man** [comment]
Thank you!

**Comment by Askank-Man** [comment]
Update v1.1.113 applied successfully and progress bar loading video page is finishing but video stream to play video link doesn't connect and there is no spinning wheel to show video stream is buffering to start playback. No Kodi error messages to report.

**Comment by 12asdfg12** [comment]
try  "Play from here"

**Comment by Askank-Man** [comment]
Tapped "play from here" but got playback failure message. Also closing Kodi and startup error message script.common.plugin cache.

**Comment by Askank-Man** [comment]
Playback failed. One or more missing items...

![Screenshot_20240729_184452_Kodi](https://github.com/user-attachments/assets/475657c2-9653-4a50-8c63-1e0957f25890)

**Comment by Askank-Man** [comment]
Add-on is working perfectly now. Thanks! As a side note there are problems with Kodi Omega v.21 unable to install Kodi add-ons needed to stream some of the videos that rely on these add-ons. Hopefully the Kodi developers will address these issues in Omega.
