### ISSUE TITLE
Problem with FFmpeg downloading 

### ISSUE THREAD

**Issue by surreydave** [dobbelina/repository.dobbelina#371]
Still unable (get error messages) to use the fantastic new video download option UWC, tried d/i FFmpeg, works manually but not with UWC. Tried it on Android (Amazon cube/stick) and Mac but no luck, have read all the comments here so far, can anyone help?

**Comment by dobbelina** [comment]
@surreydave it should be fixed in the next update Version 1.2.40.

**Comment by surreydave** [comment]
Thanks, dobbelina, it now works on my MAC but still not working on Android (Amazon cube/stick).

**Comment by surreydave** [comment]
Could FFmpeg be downloaded from a repository, like dobbelina for example so that it can be available within Kodi?
This has been done before, it was part of the Super Repository (SR) designed for Kodi 17 (not 18), this does not work now as it requires a dependency (os.Openelect.tv v4) that is no longer available.
