### ISSUE TITLE
AnimeID-Hentai - no <Next Page> or Search

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#56]
There is no -Next Page- at the bottom of the list when you open AnimeID-Hentai.

Search doesn't work in the add-on.

It pulls up a keyboard to enter a search term. So far okay, but when pushing -Done- on the keyboard only a Keyword is created. No search results are displayed.

Clicking again on the keyword opens an empty list. The website returns results (tested with working search term "lune").

It would be awesome if this could work since AnimeID-Hentai supports searching for anime-studio.

Url for searching is for example :

https://animeidhentai.com/?s=lune

and

https://animeidhentai.com/?s=lune+rex

//Merged topic Dobbelina

**Comment by 12asdfg12** [comment]
fixed
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3363364/animeidhentai.zip)

**Comment by DaisyF8** [comment]
Fixed :)

Thanks so much - awesome !

**Comment by DaisyF8** [comment]
There is still a problem so I reopened the issue.

If you search on the website for "queen bee" you get 34 results, 30 on page 1 and 4 on page 2.

In Kodi you only get 11 ?

Still great what you were able to do.

**Comment by 12asdfg12** [comment]
fixed ... probably 
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3363917/animeidhentai.zip)

p.s. don't close the issue until Dobbelina updates the addon

**Comment by DaisyF8** [comment]
(One more problem showed up)

Seems like the search now works fully.  Thanks and good job.  Results are complete and it's nice to get an overview based on searching the studio name. No other addon/website combo does this.

The one thing I noticed is sometimes an item not playing, or playing the wrong episode.  For example, if you search for "onanie" you get one result "Onanie Episode 1". On the website this plays the correct episode.  In Kodi you get a message "Oh oh - Could not find a supported link".  If you search for "chichi" however, the last result at the bottom is that onanie-episode-1.  If you start it there, it plays the wrong episode (Lilitales ep 1).

@12asdfg12 I don't know if you want to keep looking at the code... You've solved a lot allready.  And now it seems as if I know all those hentai episodes by heart :p , but I just like this kind of interaction and problem solving. I've worked with regular expressions in the past so I'm also trying to write these fixes.  But I've still got some way to go :) You're faster.

p.s. thanks for the tip, I'll leave issues open and won't rename titels anymore.  Didn't know the right etiquette.

**Comment by 12asdfg12** [comment]
try this version:
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3364608/animeidhentai.zip)

**Comment by DaisyF8** [comment]
This new version  catches the previous error perfectly.  I don't have any more things that I could test so for me this is solved.

@12asdfg12 Thanks for your followup.  If you ever need any testing done here or elsewhere, let me know.
@dobbelina  This issues seem fixed :)

**Comment by dobbelina** [comment]
Thanks 12asdfg12 for yet another great contribution!

Will update addon soon.

**Comment by dobbelina** [comment]
Issue resolved, closing thread.

**Comment by wintuxx** [comment]
Reopen
There are no next page entries in 1.1.96
