### ISSUE TITLE
AnimeIDhentai - Https error

### ISSUE THREAD

**Issue by DaisyF8** [dobbelina/repository.dobbelina#69]
Something changed on the website, everything is empty.

New episodes aren't listed.

Search results display as empty.

**Comment by dobbelina** [comment]
Site marked as broken.

**Comment by 12asdfg12** [comment]
fixed

[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3437968/animeidhentai.zip)

**Comment by dobbelina** [comment]
Awesome 12asdfg12, thanks!

**Comment by DaisyF8** [comment]
Still isn't fixed I think. I see error message "It looks like the website is down". It isn't.

I'm getting errors in the log like this
`<urlopen error unknown url type: "https>"`

Both when opening a link to a video :

`2019-07-29 18:03:32.194 T:140081223431936   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error unknown url type: "https>
                                            Traceback (most recent call last):`
...                                             
`File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 452, in _open
                                                'unknown_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1266, in unknown_open
                                                raise URLError('unknown url type: %s' % type)
                                            URLError: <urlopen error unknown url type: "https>
                                            -->End of Python script error report<--`

and when the addon tries to get art :

`WARNING: CreateLoader - unsupported protocol("https) in "https://animeidhentai.com/wp-content/uploads/2017/11/Ikkyuu-Nyuukon.jpg"`

**Comment by 12asdfg12** [comment]
the site was changed again
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3443322/animeidhentai.zip)

**Comment by DaisyF8** [comment]
Yeah fixed now. Thx

**Comment by DaisyF8** [comment]
Found another error. 

When you search (for instance "poro"), you get 3 pages of results.

If you press "Next Page" on the bottem of the first page of results then nothing happens. It shows "Looks like the website is down".

Log :

`2019-07-29 19:43:33.814 T:139630037161728   ERROR: GetDirectory - Error getting plugin://plugin.video.uwc/?channel=None&keyword&mode=661&name=Next%20Page&page=None&section=None&url=%23
2019-07-29 19:43:33.818 T:139633200876224   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.uwc/?channel=None&keyword&mode=661&name=Next%20Page&page=None&section=None&url=%23) failed`

**Comment by 12asdfg12** [comment]
fixed next page for search results:
[animeidhentai.zip](https://github.com/dobbelina/repository.dobbelina/files/3446965/animeidhentai.zip)

**Comment by DaisyF8** [comment]
Fixed I think :)

**Comment by dobbelina** [comment]
Thanks 12asdfg12,

I incorporated the latest fix in v.1.1.91
I'll keep this thread open a while if any other issue occurs.
